### PR TITLE
debian: add build-dep + push to 0.9.51

### PR DESCRIPTION
**Pull request by lynxis**
stretch will have 0.9.51 and I fixed some deprecation warnings which require 0.9.51.
@mwarning @smoe

### CODE REVIEW

**Comment by lynxis** [comment]
I would be nice of you two @smoe @mwarning could give me feedback, If everything ok, I would like to merge it on my own.

**Comment by mwarning** [comment]
@lynxis: remove the empty lines at the top of debian/changelog and change debian/compat to contain 9. Then it builds and installs without problems. But I haven't tested functionality so far.

**Comment by lynxis** [comment]
done.

**Comment by mwarning** [comment]
@lynxis please merge :-)

**Comment by lynxis** [comment]
merged

**Pull request closed without merging**
