### PR TITLE
remove dead code for removed network setting

### PR DESCRIPTION
**Pull request by mwarning**
@bluewavenet can you take a look. In case I missed something. The network setting has been removed und essentially merge with gatewayinterface.

### CODE REVIEW

**Comment by bluewavenet** [comment]
Looks good. Default gatewayinterface is br-lan in uci config, but is there a case for setting this in conf.h?

**Comment by mwarning** [comment]
I do not understand the question. gatewayinterface is stored in setting gw_interface of conf.h.

**Comment by mwarning** [comment]
I do not understand the question. gatewayinterface is stored in setting gw_interface of conf.h.

**Comment by bluewavenet** [comment]
Ah, yes sorry, I meant to say set a default in conf.h
ie:
`#define DEFAULT_GATEWAYINTERFACE "br-lan"`
and use this to fill gw_interface if not supplied in config file.

**Comment by mwarning** [comment]
br-lan is openwrt specific. That default should stay in /etc/config/nodogsplash.

**Comment by mwarning** [comment]
Anyway, that is a different discussion anyway.

**Comment by bluewavenet** [comment]
If not set in config it just errors and fails, always has, so not a problem.

I did not think br-lan was openwrt specific, rather, a very common choice for a bridge interface name on a lan. It is also the default in the nodogsplash.conf file used for other Linux distributions eg in my experience, Suse Enterprise and OpenSuse where it is the default bridge interface name as far as I remember.
No matter though.

**Pull request merged**
