### PR TITLE
Json filter

### PR DESCRIPTION
**Pull request by mwarning**
Allows "ndsctl json [ip|mac|token]".
Untested so far.

### CODE REVIEW

**Comment by bluewavenet** [comment]
This looks great. I'll close #269 and do the docs update separately.

**Comment by mwarning** [comment]
Ok, the feature should work now.

**Comment by bluewavenet** [comment]
Compiled and tested (rebased on master). Works as intended.
Typical output:
root@BlueWave:/tmp# ndsctl json 10.168.1.194 
{
"id":2,
"ip":"10.168.1.194",
"mac":"84:38:38:98:38:1a",
"added":0,
"active":1535093365,
"duration":1535093417,
"token":"96da0076",
"state":"Preauthenticated",
"downloaded":"0",
"avg_down_speed":"0.00",
"uploaded":"0",
"avg_up_speed":"0.00"
}

root@BlueWave:/tmp# ndsctl json 10.168.1.68
{
"id":1,
"ip":"10.168.1.68",
"mac":"74:de:2b:b1:70:33",
"added":1535093523,
"active":1535093878,
"duration":355,
"token":"7a4b1739",
"state":"Authenticated",
"downloaded":"3085",
"avg_down_speed":"69.53",
"uploaded":"334",
"avg_up_speed":"7.53"
}

**Comment by mwarning** [comment]
hm, might it have been better to include the other data that `ndctl json` displays?

**Pull request merged**
