### PR TITLE
simplify templater

### PR DESCRIPTION
**Pull request by mwarning**
Some code simplifications for the template engine.

### CODE REVIEW

**Comment by mwarning** [comment]
This also makes the code faster..

**Comment by mwarning** [comment]
@bluewavenet

**Comment by bluewavenet** [comment]
Looks good, indeed it should be faster. I have found the integrated FAS login page coming up noticeably quicker on my test system than the pre 3.1.0 version, as fas no longer uses this of course - now I see why.
Do you want me to compile and test?
At this rate we will keep up the release per week rate :-D

**Comment by mwarning** [comment]
I haven't tested the code. But if there is something wrong with this code - we will notice it in time.
There are quite a few things that needs fixing in the code:
- NDS probably cannot deliver content for the status page like  css or image files
- the whole code in src/http_microhttpd.c is a mess that has probably a lot of missed edge cases
- traffic control is still broken
- the status page misses template variable for the number of authenticated clients
- include blocked and trusted clients in the client list (so they can be managed)

**Comment by bluewavenet** [comment]
I'll test it fairly soon ;-)
It's a useful list. I think I will add it to the docs ToDo section.

 * I think NDS serves anything at any time if it is in the images directory so we probably just need to rename to something more generic eg pagedata or similar.
 * I'm not sure what management is needed for blocked and trusted clients. Both Binauth and FAS can dynamically trust or block using ndsctl. The problem arises in making them permanent ie which config file to write to. Binauth/FAS can implement degrees of blocking/trust by maintaining their own list of clients - this being much more flexible. In this way complexities are moved away from NDS itself.

**Comment by bluewavenet** [comment]
In fact, I have just discovered it will serve anything from pagesdir as well, possibly since v3.0.0
So .css and .jpg files are fine!

**Pull request merged**
