### PR TITLE
add setting sessiontimeout

### PR DESCRIPTION
**Pull request by mwarning**
Reintroduces a setting clienttimeout to set the session duration of an authenticated client.

### CODE REVIEW

**Comment by mwarning** [comment]
The code is untested and the name of the setting is not yet decided.

**Comment by mwarning** [comment]
@bluewavenet what is better SessionLength or SessionDuration? Or do you have a better suggestion for a different name for ClientForceTimeout?

**Comment by bluewavenet** [comment]
Personally I prefer ClientForceTimeout but I do see where you are coming from.
To have a name that unambiguously describes its function but keeping to a reasonable length is a good idea, so on that basis, I suggest:
**DefaultSessionTimeout**
It sets the default session timeout.
If not set there is no default.
Timeout rather than duration to conform with the naming of the other two idle timeout settings.

**Comment by mwarning** [comment]
DefaultSessionTimeout it is then.

**Comment by mwarning** [comment]
It just noticed that we already have DEFAULT_SESSION_TIMEOUT as the default for session_timeout. So instead fo renaming it to DEFAULT_DEFAULT_SESSION_TIMEOUT, I just use session_timeout the original variable name.

**Comment by bluewavenet** [comment]
I'll do a compile and my own tests at some stage over the weekend :-)

**Pull request merged**
