### PR TITLE
keep openwrt package files in nds repository

### PR DESCRIPTION
**Pull request by mwarning**
@bluewavenet is this what you meant?
Code is sometimes easier than words. :->

### CODE REVIEW

**Comment by bluewavenet** [comment]
#206 
Hehe :-D

**Comment by mwarning** [comment]
hm, I'm okay with putting the openwrt package as it is in this PR. But not all files from the resource folder are meant for OpenWrt. That is why the files are listed in the openwrt package Makefile.

**Comment by bluewavenet** [comment]
Yes, just have the openwrt-routing makefile copy restart.sh, nodogsplash (uci config), nodogsplash (init.d) and nodogsplash (uci-defaults) in exactly the same way as it currently does with splash.html, splash.css and splash.jpg.

**Comment by mwarning** [comment]
The splash.* files are shared with the debian package and vanilla installation (`make install`) of NDS. So we can't move them into the `openwrt/nodogsplash/files/`.

**Comment by mwarning** [comment]
ok, since we agree on this part so far.

**Pull request merged**
