### PR TITLE
put fas code into block

### PR DESCRIPTION
**Pull request by mwarning**
Put some fas code behind `if (config->fas_port)`.

### CODE REVIEW

**Comment by mwarning** [comment]
@bluewavenet

**Comment by bluewavenet** [comment]
@mwarning 
It compiles ok but fails with the log message:

> Thu Jul 25 10:44:14 2019 daemon.crit nodogsplash[15017]: safe_strdup called with NULL which would have crashed strdup. Bailing out.

**Comment by mwarning** [comment]
@bluewavenet try again

**Comment by bluewavenet** [comment]
That's better, seems to work ok now ;-)

**Comment by mwarning** [comment]
ok, this makes the code a bit better to understand and prevents side effects from FAS code.

**Pull request merged**
