### PR TITLE
Fixstyle

### PR DESCRIPTION
**Pull request by lynxis**
Hi @bluewavenet 
Hi @mwarning 

I just figured out, that `make checkstyle` in our travis script was broken.
Also `make fixstyle` was broken.

Should we merge this huge diff? (run make filxstyle)

### CODE REVIEW

**Comment by bluewavenet** [comment]
You will have to help me a little with my understanding of this.
Normally, when should we be running make fixstyle? Before doing a PR?

**Comment by lynxis** [comment]
Travis is run `make checkstyle` on every pull request, which leads to use `astyle`

**Comment by mwarning** [comment]
@lynxis looks good, thanks

**Comment by lynxis** [comment]
old and deprecated.

**Pull request closed without merging**
