### PR TITLE
Fix counter reset

### LINKED ISSUE #301: Client Upload/Download counters stop updating after session timeout and reauthentication
@mwarning 
Happens with v3x. The values given by ndsctl for a client's upload download totals at the time of session timeout, remain the same (stuck) with no further update after the client authenticates again.
At session timeout, the client changes from authenticated to preauthenticated, with the upload counters kept.

In version 2x the behaviour was (I think) to remove the client from the client list at session timeout (aka clientforcetimeout interval). Upon reconnection in v2, all the client data was reset of course.

I will have a look at the code later when I have time, but you are probably more familiar with that part than I am, so if you can take a quick look... ;-)

### PR DESCRIPTION
**Pull request by mwarning**
Should fix #301

### CODE REVIEW

**Comment by mwarning** [comment]
@bluewavenet can you give it a test?

**Comment by bluewavenet** [comment]
Wow! I did not mean to keep you up half the night :-D
Nearly fixed.
It works with a manual ndsctl deauth, resetting the counters and issuing a new token, but sessiontimeout is ignored now.

**Comment by mwarning** [comment]
Hm, what do you mean with sessiontimeout is ignored?

**Comment by bluewavenet** [comment]
If sessiontimeout is set (in config), before this PR clients were deauthed automatically on the expiration of sessiontimeout. With this PR they never get deauthed automatically.

**Comment by bluewavenet** [comment]
I've just noticed that when client status is preauth, ndsctl clients and json return "duration" as current time. But when authed, they show time in seconds since authentication which is as it should be.

**Comment by bluewavenet** [comment]
That looks good for duration.
Looking at the code, I can't see where sessiontimeout is handled....

**Comment by bluewavenet** [comment]
@mwarning 
We are all good! My fault with sessiontimeout - it is working.
The sdk I'm using had the old version of the init.d script without sessiontimeout

**Comment by bluewavenet** [comment]
Github is saying Travis has not completed, but it has.
Apart from that, ready to merge.

**Comment by mwarning** [comment]
Good, I couldn't see why sessiontimeout would not work.

**Comment by bluewavenet** [comment]
Oh the irony! It was me that spotted the issue with init.d script - then I promptly forgot all about it.

**Pull request merged**
