### PR TITLE
update docs

### PR DESCRIPTION
**Pull request by mwarning**
Update the documentation for the 3.0.0 release.

@bluewavenet please review, change and extend as you like.

### CODE REVIEW

**Comment by bluewavenet** [comment]
I need 48 hour days :-D

**Comment by mwarning** [comment]
48h days sounds fine to me. xD

note to self: The index.rst should have a nicer entry for FAS.

**Comment by bluewavenet** [comment]
I'll update the fas parts and go through the rest as well. Is an example binauth script available?

**Comment by mwarning** [comment]
Yes, https://github.com/nodogsplash/nodogsplash/blob/master/docs/source/binauth.rst

**Comment by mwarning** [comment]
I think it is comfortable to have most 3.0.0 changes in master sooner rather than later.
Feel free to work on the fas authentication.

**Pull request merged**
