### PR TITLE
locking issues

### PR DESCRIPTION
**Pull request by lynxis**
Fix a dead lock and a client list lock.

* [ ] needs testing

Please let me merge this (by cherry-picking it to the master)

### CODE REVIEW

**Comment by bluewavenet** [comment]
Looks good! Shall we push a new branch ie nodogsplash:feature_client_list?  I am all set up to do some rapid testing.

**Comment by lynxis** [comment]
@bluewavenet does this PR also fix the errors which lead to 1a9420043b54343d1508e98f31b17204b06103af ? Do you have any further information what was the problem on the locking?

**Comment by lynxis** [comment]
you can also checkout this PR with git `git fetch origin pull/453/head ; git checkout -b locking FETCH_HEAD`

**Comment by bluewavenet** [comment]
@lynxis 
See my notes in issue #409 
I found:

> Interesting in that if LOCK_CLIENT_LIST is disabled in the code it makes no difference so I suspect it is not working

Your fixes here are very much related but probably not the whole story behind #409

**Comment by bluewavenet** [comment]
@lynxis 
Issue #387 , particularly the comments towards the end, is interesting.

**Pull request merged**
