### PR TITLE
support for ipset

### PR DESCRIPTION
**Pull request by vavrecan**

### CODE REVIEW

**Comment by lynxis** [comment]
hey @vavrecan 
thanks for your PR.
Please document the ipset in the example configuration under /resources/nodogsplash.conf
About allow un/auth by token: LGTM

**Comment by vavrecan** [comment]
uhh, can you please help with nodogsplash.conf modifications? I was not really sure whats the best way to modify it. Basically syntax is 

FirewallRule allow tcp port [port number] ipset [ipset rule name]
FirewallRule allow tcp port 443 ipset WHITELISTED_IPS

**Comment by mwarning** [comment]
@vavrecan is this ready to be merged? There are plans to do a release very soon.

**Comment by vavrecan** [comment]
sure you can go on, @lynxis is it ok with you also?

**Comment by lynxis** [comment]
Acked-by: Alexander Couzens <lynxis@fe80.eu>

LGTM

**Pull request merged**
